{
 "title": "Jaxy_Monitoring",
 "tags": [
  "prometheus",
  "node",
  "misc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_load1{job=\"jaxy_monitoring\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"jaxy_monitoring\"}\t"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "base:cpu_available_processors" }
   ]
  },
  {
   "title": "Memory Used Heap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "base:memory_used_heap_bytes" }
   ]
  },
  {
   "title": "Memory Max Heap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "base:memory_max_heap_bytes" }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "application:exceptions_count" }
   ]
  },
  {
   "title": "Failure Authentication",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application:failure_authentication_count"
    }
   ]
  },
  {
   "title": "CPU System Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "base:cpu_system_load_average", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "Thread Count ( daemon and non-daemon threads )",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "base:thread_count", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Memory used heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "base:memory_used_heap_bytes", "legendFormat": "buffers" }
   ]
  }
 ]
}